#ifndef __PHRASE_HPP__
#define __PHRASE_HPP__

enum Phrase {
    PHRASE_DEFAULT_RUNTIME_ERROR_MESSAGE,
    PHRASE_DEFAULT_UNKNOWN_ERROR_MESSAGE,
    PHRASE_ERROR_MESSAGE_INVALID_EXECUTION_ACTION,
    PHRASE_ERROR_MESSAGE_INVALID_EXECUTION_MODE,
    PHRASE_ERROR_MESSAGE_INVALID_LIST_OPTION,
    PHRASE_ERROR_MESSAGE_INVALID_NUMBER_OPTION,
    PHRASE_ERROR_MESSAGE_INVALID_TIMESTAMP,
    PHRASE_MESSAGE_HELP_EXAMPLE_PART_1,
    PHRASE_MESSAGE_HELP_EXAMPLE_PART_2,
    PHRASE_UNKNOWN
};

#endif
