#ifndef __PHRASE_HPP__
#define __PHRASE_HPP__

enum Phrase {
    PHRASE_DEFAULT_RUNTIME_ERROR_MESSAGE,
    PHRASE_DEFAULT_UNKNOWN_ERROR_MESSAGE,
    PHRASE_ERROR_MESSAGE_INVALID_EXECUTION_ACTION,
    PHRASE_UNKNOWN
};

#endif
