#ifndef __PHRASE_HPP__
#define __PHRASE_HPP__

enum Phrase {
    PHRASE_HELLO_WORLD,
    PHARSE_ERROR_ARG_NO_EXECUTION_MODE,
    PHARSE_ERROR_ARG_INVALID_EXECUTION_MODE,
    PHARSE_ERROR_ARG_NO_EXECUTION_ACTION,
    PHARSE_ERROR_ARG_INVALID_EXECUTION_ACTION,
    PHARSE_ERROR_ARG_NO_PATH_FILE,
    PHARSE_ERROR_ARG_NO_SOURCE,
    PHARSE_ERROR_ARG_NO_DESTINATION,
    PHARSE_ERROR_OPEN_FILE_FAILED,
    PHARSE_ERROR_FORMAT_CONVERSION_FAILED
};

#endif
