#ifndef __PHRASE_HPP__
#define __PHRASE_HPP__

enum Phrase {
    PHRASE_HELLO_WORLD,
    PHARSE_ERROR_ARG_NO_EXECUTION_MODE,
    PHARSE_ERROR_ARG_INVALID_EXECUTION_MODE,
    PHARSE_ERROR_ARG_NO_EXECUTION_ACTION,
    PHARSE_ERROR_ARG_INVALID_EXECUTION_ACTION,
    PHARSE_ERROR_ARG_NO_PATH_FILE,
    PHARSE_ERROR_ARG_NO_SOURCE,
    PHARSE_ERROR_ARG_NO_DESTINATION,
    PHARSE_ERROR_DIRHIST_FILE_NOT_FOUND,
    PHARSE_ERROR_OPEN_FILE_FAILED,
    PHARSE_ERROR_FORMAT_CONVERSION_FAILED,
    PHARSE_ERROR_DOCUMENT_IS_NOT_DEFINE,
    PHARSE_ERROR_PRINT_ACTION_IS_NOT_DEFINE,
    PHARSE_ERROR_EXECUTE_ACTION_IS_NOT_DEFINE,
    PHARSE_ERROR_NO_EXECUTABLE_ACTION_AVAILABLE,
    PHARSE_ERROR_FORMAT_DIRHIST_FILE_IS_INCORRECT,
    PHARSE_ERROR_COORDINATE_MISALIGNMENT,
    PHARSE_ERROR_AUTO_CORRECTION_FAILED,
    PHARSE_ERROR_UNEXPECTED_DESTINATION,
    PHARSE_MESSAGE_ALREADY_ON_FIRST_DIRECTORY,
    PHARSE_MESSAGE_ALREADY_ON_LAST_DIRECTORY,
    PHARSE_MESSAGE_TOO_MANY_DIRECTORIES_TO_GO_BACK,
    PHARSE_MESSAGE_TOO_MANY_DIRECTORIES_TO_GO_AHEAD
};

#endif
